spring:
  liquibase:
    enabled: false

server:
  port: 8080

access-token:
  prefix: AT.

key-val-repository:
  global-prefix: RTCMS4J_CORE_SCOPE_
  topic: NOTIFY_EVENT_TOPIC

json:
  meta-schema-class-path: json/schema/meta-schema.json
