spring:
  liquibase:
    enabled: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

server:
  port: 8080

access-token:
  prefix: AT.

key-val-repository:
  global-prefix: RTCMS4J_CORE_SCOPE_
  topic: NOTIFY_EVENT_TOPIC

json:
  meta-schema-class-path: json/schema/meta-schema.json

default:
  pagination:
    page-size: 10

roles:
  super-admin-role: rtcms4j-super-admin
